#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# #SWPH task 4: the Switchboard on the phone, end to end, against the REAL hosted rendezvous at
# https://join.relay-terminal.ai — the inbox row, the cards by stage, a card's page and thread, an
# answer, a note, a move, a new card, search, Discuss / Stop / Plan, Execute and Verify, the
# `card_waiting` push, the offline queue, what a guest and a `view` device are refused, that no
# path of this machine reaches the phone, and the iPad and landscape layouts.
#
#   docs/qa_evidence/2026-09-21-swph-hosted-drive/drive.sh [build-dir [source-dir]]
#
# One command, about eight minutes, one jail, one Relay. It opens with #FR1C's steps 14-19 on the
# same build — they are how this run gets a phone paired by typed code at `full`, a second device,
# notifications switched on and a desktop that has been switched off and on again — and then walks
# this card's thirteen steps on that same paired phone. #FR1C's and #PH0N's harnesses are imported
# by path, not copied (`run.py`).
#
# `build-dir` holds `relay`; `source-dir` is the tree it was built from (its `remote/` is the
# sidecar that binary starts, its `backend/` the worker). The default is this checkout's `build/`
# and the checkout; the recorded run is a clean export of `main` (README, "Provenance").
#
# The sandbox is #PH0N's: HOME/XDG_*/XDG_RUNTIME_DIR/TMPDIR under one short mktemp directory,
# RELAY_KEYRING=off, Xvfb, a fake model on loopback. Two things are added. PATH is cut down to the
# system's, so no `claude` or `codex` of the owner's can be found and offered as a verifier. And
# RELAY_REMOTE_DIR points at a two-file tap (`sidecar_tap.py`) that runs the real sidecar and
# writes down what the hub hands each channel and the push service — see that file for why.
#
# Do not edit this file while a run is going: bash reads a script by byte offset as it runs.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
out=$PWD
root=$(cd ../../.. && pwd)
ph0n=$root/docs/qa_evidence/2026-09-21-ph0n-hosted-drive
fr1c=$root/docs/qa_evidence/2026-09-21-fr1c-hosted-drive
build=$(cd "${1:-$root/build}" && pwd)
source_dir=$(cd "${2:-$root}" && pwd)
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
unset PORKBUN_API_KEY PORKBUN_SECRET_API_KEY CLAUDE_CODE_MESSAGING_TOKEN ANTHROPIC_API_KEY OPENAI_API_KEY
port=${RELAY_QA_PORT:-$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1])')}

[[ -x $build/relay ]] || { echo "no $build/relay; scripts/relay-build first"; exit 1; }
[[ -f $source_dir/remote/gui_host.py ]] || { echo "$source_dir is not a Relay source tree"; exit 1; }
[[ -f $ph0n/run.py && -f $fr1c/run.py ]] || { echo "the #PH0N / #FR1C harnesses are missing"; exit 1; }
for tool in Xvfb xdotool import tesseract xmessage git; do
  command -v "$tool" >/dev/null || { echo "$tool is not on PATH"; exit 1; }
done
health() { curl -s -m 8 https://join.relay-terminal.ai/v1/health; }
health | grep -q '"ok": true' || { echo "join.relay-terminal.ai/v1/health does not answer from here"; exit 1; }
health_before=$(health)

# Which tree this run is of. The phone runs the app **as deployed**, so the served hashes against
# the source tree's are the line that says whether a red step is the code or the deploy.
{
  echo "run started    $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "checkout HEAD  $(git -C "$root" rev-parse --short HEAD) $(git -C "$root" log -1 --format=%s)"
  echo "source-dir     $source_dir$( [[ -f $source_dir/../REV ]] && echo "  (git archive of $(cut -c1-8 "$source_dir/../REV"))")"
  echo "relay binary   $build/relay  $(date -r "$build/relay" '+%Y-%m-%d %H:%M:%S')  sha256 $(sha256sum "$build/relay" | cut -c1-12)"
  echo "health before  $health_before"
  for f in index.html app.js board.js board.css boardmd.js outbox.js rrp.js sw.js pane.js pane.css pane-theme.css style.css meet.js; do
    printf 'served %-15s %s  source %s\n' "$f" \
      "$(curl -s -m 15 "https://join.relay-terminal.ai/$f" | sha256sum | cut -c1-12)" \
      "$(sha256sum "$source_dir/app/$f" | cut -c1-12)"
  done
} >"$out/provenance.txt"

display=
for n in $(seq 140 199); do
  [[ -e /tmp/.X11-unix/X$n || -e /tmp/.X$n-lock ]] && continue
  if (set -o noclobber; echo $$ >"/tmp/.relay-e2e-X$n.lock") 2>/dev/null; then
    display=:$n
    lock=/tmp/.relay-e2e-X$n.lock
    break
  fi
done
[[ -z $display ]] && { echo "no free X display"; exit 1; }
echo "display $display"

jail=$(mktemp -d /tmp/swph.XXXXXX)
export HOME="$jail/home" XDG_CONFIG_HOME="$jail/config" XDG_DATA_HOME="$jail/data"
export XDG_CACHE_HOME="$jail/cache" XDG_STATE_HOME="$jail/state" XDG_RUNTIME_DIR="$jail/run" TMPDIR="$jail/tmp"
export RELAY_KEYRING=off
work="$jail/harbour"
mkdir -p "$HOME" "$XDG_CONFIG_HOME/RelayTerminal" "$XDG_CONFIG_HOME/relay" "$XDG_DATA_HOME" \
         "$XDG_CACHE_HOME" "$XDG_STATE_HOME" "$TMPDIR" "$jail/tap/remote"
mkdir -m 700 -p "$XDG_RUNTIME_DIR"
python3 "$out/fixture.py" "$work" "$source_dir" || { echo "the fixture board was not made"; rm -rf "$jail"; exit 1; }

# Remote control OFF is what a fresh profile ships with; step 14 turns it on from the plug menu.
cat >"$jail/relay.conf.template" <<'CONF'
[isolation]
enabled=false

[security]
approvals_chosen=true

[provider]
preset=local:fake

[models]
tier/flash=local:fake|fake|
tier/lite=local:fake|fake|

[instructions]
onboarded=true

[terminal]
shell_integration=true
CONF
cp "$jail/relay.conf.template" "$XDG_CONFIG_HOME/RelayTerminal/relay.conf"
: >"$out/requests.jsonl"
python3 "$out/fake-model.py" "$port" "$out/requests.jsonl" "$ph0n/fake-model.py" &
fake_pid=$!
for i in $(seq 1 20); do
  curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' && break
  sleep 0.5
done
curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' \
  || { echo "the fake model did not come up on 127.0.0.1:$port"; kill "$fake_pid" 2>/dev/null; rm -rf "$jail"; exit 1; }
printf '{"version": 1, "endpoints": [{"id": "local:fake", "label": "Fake", "base_url": "http://127.0.0.1:%s/v1", "model": "fake", "server": "openai-compatible", "context_window": 131072, "tools": true}]}\n' \
  "$port" >"$XDG_CONFIG_HOME/relay/local-models.json"

# The tap: the real sidecar, plus a line per board message and per push (sidecar_tap.py).
printf 'import os\n__path__.append(os.environ["SWPH_REAL_REMOTE"])\n' >"$jail/tap/remote/__init__.py"
cp "$out/sidecar_tap.py" "$jail/tap/remote/gui_host.py"
export RELAY_REMOTE_DIR="$jail/tap" SWPH_REAL_REMOTE="$source_dir/remote" SWPH_TAP_LOG="$jail/tap.jsonl"
: >"$SWPH_TAP_LOG"

Xvfb "$display" -screen 0 2600x1300x24 >/dev/null 2>&1 &
xvfb_pid=$!
cleanup() {
  pkill -P $$ -f "$build/relay" 2>/dev/null
  pkill -f "$build/relay --workspace $jail" 2>/dev/null
  # A run that was killed never stopped its browsers; their profiles live in the jail's TMPDIR.
  pkill -f -- "--user-data-dir=$jail/" 2>/dev/null
  kill "$xvfb_pid" "$fake_pid" 2>/dev/null
  rm -f "${lock:-/dev/null}"
  rm -rf "$jail"
}
trap cleanup EXIT
sleep 1
export DISPLAY=$display

export RELAY_REMOTE_PAIR_FILE="$jail/pair-url.txt"
export RELAY_REMOTE_INVITE_FILE="$jail/invite-url.txt"
export RELAY_REMOTE_PAIR_CODE_FILE="$jail/pair-code.txt"
export RELAY_QA_OUT=$out RELAY_QA_WORK="$work" RELAY_QA_JAIL=$jail RELAY_QA_BUILD=$build
export RELAY_QA_PH0N=$ph0n RELAY_QA_FR1C=$fr1c RELAY_QA_SOURCE=$source_dir
( cd "$root" && python3 "$out/run.py" ) 2>&1 | tee "$out/run.log"
status=${PIPESTATUS[0]}

cat "$XDG_DATA_HOME"/relay/remote/audit-*.jsonl >"$out/audit.jsonl" 2>/dev/null
rm -f "$out/.share-probe.png" "$out/.ocr.png"
python3 - "$out/audit.jsonl" >"$out/audit.txt" 2>/dev/null <<'PY'
import json, sys
for line in open(sys.argv[1]):
    row = json.loads(line)
    kind = row.pop("kind", "?")
    row.pop("at", None)
    print(f"{kind:20} " + " ".join(f"{k}={v!r}" for k, v in row.items()))
PY
rm -f "$out/audit.jsonl"
{
  echo "health after   $(health)"
  echo "run ended      $(date '+%Y-%m-%d %H:%M:%S %Z')"
} >>"$out/provenance.txt"

echo "screenshots and logs in $out"
exit "$status"
