#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# #PH0N wave 3: the always-on phone remote control, end to end, against the REAL hosted rendezvous
# at https://join.relay-terminal.ai — a fresh desktop profile, a headless "phone", a headless guest,
# and a fake model that costs nothing.
#
#   docs/qa_evidence/2026-09-21-ph0n-hosted-drive/drive.sh [build-dir]
#
# This script is only the sandbox: the isolation, the X server, the fake model. Everything after
# that — starting and restarting Relay, the clicks, the browsers, every screenshot — is `run.py`,
# because step 12 (quit Relay and start it again on the same profile) means the run owns the
# Relay process, not this script.
#
# Writes NN-<side>-<what>.png next to this script (side: desktop, share, phone, guest), plus
# relay-stderr.log, run.log, notes.txt, requests.jsonl (what the fake model was sent),
# provenance.txt and audit.txt.
#
# Isolation: HOME, XDG_CONFIG_HOME, XDG_DATA_HOME, XDG_CACHE_HOME **and XDG_RUNTIME_DIR and
# TMPDIR**, all under one short mktemp directory (Chrome's singleton socket path has a hard length
# limit). RELAY_KEYRING=off, so the run cannot reach the owner's provider keys and cannot overwrite
# his real remote identity key: the identity this run registers at join.relay-terminal.ai is a
# throwaway minted in the jail, and it is gone with the jail.
#
# What it needs on the machine: Xvfb, xdotool, ImageMagick's `import`, a Chrome or Chromium, and
# a route to https://join.relay-terminal.ai.
# Do not edit this file while a run is going: bash reads a script by byte offset as it runs, so an
# edit above the line it is on makes it re-execute earlier lines — on 2026-09-21 that started a
# second run.py in the same jail on top of the first one's profile.
#
# RELAY_QA_GDB=1 runs Relay under gdb (batch), so a crash leaves a full backtrace in the stderr log.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
out=$PWD
root=$(cd ../../.. && pwd)
build=${1:-$root/build}
# A free loopback port for the fake model, found now rather than fixed: a fixed one is what a
# run left behind by an earlier drive still holds, and Relay then talks to *that* run's model.
port=${RELAY_QA_PORT:-$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1])')}

[[ -x $build/relay ]] || { echo "no $build/relay; scripts/relay-build first"; exit 1; }
for tool in Xvfb xdotool import; do
  command -v "$tool" >/dev/null || { echo "$tool is not on PATH"; exit 1; }
done
curl -s -m 5 https://join.relay-terminal.ai/v1/health | grep -q '"ok": true' \
  || { echo "join.relay-terminal.ai/v1/health does not answer from here"; exit 1; }

# Which tree this run is of: the Python half (remote/, app/ as served by the rendezvous) is what is
# deployed, `build/relay` is whatever was last built from this checkout, and several sessions commit
# to it while a run is going.
{
  echo "HEAD          $(git -C "$root" rev-parse --short HEAD) $(git -C "$root" log -1 --format=%s)"
  echo "build/relay   $(date -r "$build/relay" '+%Y-%m-%d %H:%M:%S')"
  echo "dirty files   $(git -C "$root" status --porcelain | wc -l)"
  git -C "$root" status --porcelain -- app remote rendezvous src | sed 's/^/  /'
  echo "served app.js $(curl -s -m 10 https://join.relay-terminal.ai/app.js | sha256sum | cut -c1-12)  repo app.js $(sha256sum "$root/app/app.js" | cut -c1-12)"
} >"$out/provenance.txt"

# A free display, locked with noclobber so two drives cannot take the same one.
display=
for n in $(seq 140 199); do
  [[ -e /tmp/.X11-unix/X$n || -e /tmp/.X$n-lock ]] && continue
  if (set -o noclobber; echo $$ >"/tmp/.relay-e2e-X$n.lock") 2>/dev/null; then
    display=:$n
    lock=/tmp/.relay-e2e-X$n.lock
    break
  fi
done
[[ -z $display ]] && { echo "no free X display"; exit 1; }
echo "display $display"

jail=$(mktemp -d)                       # /tmp/tmp.XXXXXXXXXX: short, for the socket paths
export HOME="$jail/home" XDG_CONFIG_HOME="$jail/config" XDG_DATA_HOME="$jail/data"
export XDG_CACHE_HOME="$jail/cache" XDG_RUNTIME_DIR="$jail/run" TMPDIR="$jail/tmp"
export RELAY_KEYRING=off
mkdir -p "$HOME" "$XDG_CONFIG_HOME/RelayTerminal" "$XDG_CONFIG_HOME/relay" "$XDG_DATA_HOME" \
         "$XDG_CACHE_HOME" "$jail/work" "$TMPDIR"
mkdir -m 700 -p "$XDG_RUNTIME_DIR"
# Remote control OFF is what a fresh profile ships with; nothing about it is written here, so step
# 1 is the shipped default and not this script's word for it.
#
# The Flash and Lite tiers point at the fake model too: the summaries role (a recap) and the
# chores role (a pane title) resolve to those tiers, and with no list a tier falls back to the
# default provider's row — Relay Free — so a "keyring off" profile still spends hosted inference
# on its first recap (run 3 of this drive did, and printed a real model's recap). Main is the
# pane's own model, `provider/preset` above.
# Isolation off: the agent worker runs under `systemd-run --user --scope` with the session bus
# address stripped from its environment (src/Pane.h, card #Y4RX), so it looks for the bus at
# $XDG_RUNTIME_DIR/bus — which in this jail does not exist, and the worker exits 1 in 40 ms
# ("The agent worker exited." on every pane). Every other Xvfb drive in docs/qa_evidence does the
# same; a real desktop's runtime dir has the bus.
cat >"$XDG_CONFIG_HOME/RelayTerminal/relay.conf" <<'CONF'
[isolation]
enabled=false

[security]
approvals_chosen=true

[provider]
preset=local:fake

[models]
tier/flash=local:fake|fake|
tier/lite=local:fake|fake|

[instructions]
onboarded=true

[terminal]
shell_integration=true
CONF
: >"$out/requests.jsonl"
python3 "$out/fake-model.py" "$port" "$out/requests.jsonl" &
fake_pid=$!
for i in $(seq 1 20); do
  curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' && break
  sleep 0.5
done
curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' \
  || { echo "the fake model did not come up on 127.0.0.1:$port"; kill "$fake_pid" 2>/dev/null; exit 1; }
printf '{"version": 1, "endpoints": [{"id": "local:fake", "label": "Fake", "base_url": "http://127.0.0.1:%s/v1", "model": "fake", "server": "openai-compatible", "context_window": 131072, "tools": true}]}\n' \
  "$port" >"$XDG_CONFIG_HOME/relay/local-models.json"
Xvfb "$display" -screen 0 2600x1300x24 >/dev/null 2>&1 &
xvfb_pid=$!
trap 'kill "$xvfb_pid" "$fake_pid" 2>/dev/null; rm -f "${lock:-/dev/null}"; rm -rf "$jail"' EXIT
sleep 1
export DISPLAY=$display

# The pairing and invite links carry one-time secrets and are never logged: Relay writes each out
# only when the matching QA-only variable names a file (RemoteShare::handle).
export RELAY_REMOTE_PAIR_FILE="$jail/pair-url.txt"
export RELAY_REMOTE_INVITE_FILE="$jail/invite-url.txt"
export RELAY_QA_OUT=$out RELAY_QA_WORK="$jail/work" RELAY_QA_JAIL=$jail RELAY_QA_BUILD=$build
( cd "$root" && python3 "$out/run.py" ) 2>&1 | tee "$out/run.log"
status=${PIPESTATUS[0]}

# Every audit file the two Relay processes wrote (one per month, numbered parts past a size), in
# order; the probe image `run.py` reads the share window's rows from is the run's own, not evidence.
cat "$XDG_DATA_HOME"/relay/remote/audit-*.jsonl >"$out/audit.jsonl" 2>/dev/null
rm -f "$out/.share-probe.png"
python3 - "$out/audit.jsonl" >"$out/audit.txt" 2>/dev/null <<'PY'
import json, sys
for line in open(sys.argv[1]):
    row = json.loads(line)
    kind = row.pop("kind", "?")
    row.pop("at", None)
    print(f"{kind:20} " + " ".join(f"{k}={v!r}" for k, v in row.items()))
PY
rm -f "$out/audit.jsonl"

echo "screenshots and logs in $out"
exit "$status"
