#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# #FR1C task 4: pairing a phone WITHOUT friction, end to end, against the REAL hosted rendezvous at
# https://join.relay-terminal.ai — the plug menu's "Pair a phone…", the code typed on the phone,
# a burned code, iOS install-first, notifications offered on arrival, and the plug menu's switch.
#
#   docs/qa_evidence/2026-09-21-fr1c-hosted-drive/drive.sh [build-dir]
#
# One command (about five minutes), two halves, one jail:
#   * steps 14-19, this card's new path, on a fresh profile with remote control off;
#   * then the profile is wiped and #PH0N's thirteen steps are re-run on the same build, because
#     the harness is shared and this card changed the desktop entry point the third of them uses.
#
# The sandbox — HOME/XDG_*/XDG_RUNTIME_DIR/TMPDIR under one short mktemp directory, RELAY_KEYRING=off,
# Xvfb, the fake model — is #PH0N's, and so are the fake model and every helper `run.py` imports:
# this drive extends that harness rather than forking it (`run.py` loads it by path).
#
# Do not edit this file while a run is going: bash reads a script by byte offset as it runs.
#
# RELAY_QA_GDB=1 runs Relay under gdb (batch), so a crash leaves a full backtrace in the stderr log.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
out=$PWD
root=$(cd ../../.. && pwd)
ph0n=$root/docs/qa_evidence/2026-09-21-ph0n-hosted-drive
build=${1:-$root/build}
port=${RELAY_QA_PORT:-$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1])')}

[[ -x $build/relay ]] || { echo "no $build/relay; scripts/relay-build first"; exit 1; }
[[ -f $ph0n/run.py ]] || { echo "the #PH0N harness is not at $ph0n"; exit 1; }
for tool in Xvfb xdotool import; do
  command -v "$tool" >/dev/null || { echo "$tool is not on PATH"; exit 1; }
done
curl -s -m 5 https://join.relay-terminal.ai/v1/health | grep -q '"ok": true' \
  || { echo "join.relay-terminal.ai/v1/health does not answer from here"; exit 1; }

# Which tree this run is of. The phone runs the app **as deployed**, so the served hashes against
# the repo's are the line that says whether a red step is the code or the deploy.
{
  echo "HEAD          $(git -C "$root" rev-parse --short HEAD) $(git -C "$root" log -1 --format=%s)"
  echo "build/relay   $(date -r "$build/relay" '+%Y-%m-%d %H:%M:%S')"
  echo "dirty files   $(git -C "$root" status --porcelain | wc -l)"
  git -C "$root" status --porcelain -- app remote rendezvous src | sed 's/^/  /'
  for f in index.html app.js meet.js pane.js pane.css style.css viewport.js; do
    printf 'served %-12s %s  repo %s\n' "$f" \
      "$(curl -s -m 15 "https://join.relay-terminal.ai/$f" | sha256sum | cut -c1-12)" \
      "$(sha256sum "$root/app/$f" | cut -c1-12)"
  done
} >"$out/provenance.txt"

display=
for n in $(seq 140 199); do
  [[ -e /tmp/.X11-unix/X$n || -e /tmp/.X$n-lock ]] && continue
  if (set -o noclobber; echo $$ >"/tmp/.relay-e2e-X$n.lock") 2>/dev/null; then
    display=:$n
    lock=/tmp/.relay-e2e-X$n.lock
    break
  fi
done
[[ -z $display ]] && { echo "no free X display"; exit 1; }
echo "display $display"

jail=$(mktemp -d)
export HOME="$jail/home" XDG_CONFIG_HOME="$jail/config" XDG_DATA_HOME="$jail/data"
export XDG_CACHE_HOME="$jail/cache" XDG_RUNTIME_DIR="$jail/run" TMPDIR="$jail/tmp"
export RELAY_KEYRING=off
mkdir -p "$HOME" "$XDG_CONFIG_HOME/RelayTerminal" "$XDG_CONFIG_HOME/relay" "$XDG_DATA_HOME" \
         "$XDG_CACHE_HOME" "$jail/work" "$TMPDIR"
mkdir -m 700 -p "$XDG_RUNTIME_DIR"
# Remote control OFF is what a fresh profile ships with, and step 14 is about a desktop that has
# never had it on: nothing about it is written here. The template is kept because `run.py` wipes
# the profile between the two halves and puts this exact file back.
cat >"$jail/relay.conf.template" <<'CONF'
[isolation]
enabled=false

[security]
approvals_chosen=true

[provider]
preset=local:fake

[models]
tier/flash=local:fake|fake|
tier/lite=local:fake|fake|

[instructions]
onboarded=true

[terminal]
shell_integration=true
CONF
cp "$jail/relay.conf.template" "$XDG_CONFIG_HOME/RelayTerminal/relay.conf"
: >"$out/requests.jsonl"
python3 "$ph0n/fake-model.py" "$port" "$out/requests.jsonl" &
fake_pid=$!
for i in $(seq 1 20); do
  curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' && break
  sleep 0.5
done
curl -s -m 1 "http://127.0.0.1:$port/v1/models" | grep -q '"fake"' \
  || { echo "the fake model did not come up on 127.0.0.1:$port"; kill "$fake_pid" 2>/dev/null; exit 1; }
printf '{"version": 1, "endpoints": [{"id": "local:fake", "label": "Fake", "base_url": "http://127.0.0.1:%s/v1", "model": "fake", "server": "openai-compatible", "context_window": 131072, "tools": true}]}\n' \
  "$port" >"$XDG_CONFIG_HOME/relay/local-models.json"
Xvfb "$display" -screen 0 2600x1300x24 >/dev/null 2>&1 &
xvfb_pid=$!
trap 'kill "$xvfb_pid" "$fake_pid" 2>/dev/null; rm -f "${lock:-/dev/null}"; rm -rf "$jail"' EXIT
sleep 1
export DISPLAY=$display

# The three QA-only hooks. Each is written only when its variable names a file, because each
# carries a one-time secret: the pairing link's fragment, the invite's, and — new for this card —
# the pairing code and its PIN, which is what the owner types on the phone (RemoteShare::handle).
export RELAY_REMOTE_PAIR_FILE="$jail/pair-url.txt"
export RELAY_REMOTE_INVITE_FILE="$jail/invite-url.txt"
export RELAY_REMOTE_PAIR_CODE_FILE="$jail/pair-code.txt"
export RELAY_QA_OUT=$out RELAY_QA_WORK="$jail/work" RELAY_QA_JAIL=$jail RELAY_QA_BUILD=$build
export RELAY_QA_PH0N=$ph0n
( cd "$root" && python3 "$out/run.py" ) 2>&1 | tee "$out/run.log"
status=${PIPESTATUS[0]}

# The audit of the second half (the first half's is written before the profile is wiped).
cat "$XDG_DATA_HOME"/relay/remote/audit-*.jsonl >"$out/audit.jsonl" 2>/dev/null
rm -f "$out/.share-probe.png"
python3 - "$out/audit.jsonl" >"$out/audit.txt" 2>/dev/null <<'PY'
import json, sys
for line in open(sys.argv[1]):
    row = json.loads(line)
    kind = row.pop("kind", "?")
    row.pop("at", None)
    print(f"{kind:20} " + " ".join(f"{k}={v!r}" for k, v in row.items()))
PY
rm -f "$out/audit.jsonl"

echo "screenshots and logs in $out"
exit "$status"
